Repository framgia/sph_sunbnb_sim, pull requests merged in 2024-03, with the labels that each got.

#8 added models related to listings
  backend/app/Enums/AccommodationType.php
  backend/app/Enums/Amenity.php
  backend/app/Enums/ExperienceType.php
  backend/app/Enums/Inclusion.php
  backend/app/Enums/ListingStatus.php
  backend/app/Models/Accommodation.php
  backend/app/Models/Calendar.php
  backend/app/Models/Experience.php
  backend/app/Models/Listing.php
  backend/app/Models/Media.php
  backend/app/Models/Review.php
  backend/database/migrations/2024_03_04_070040_create_listings_table.php
  backend/database/migrations/2024_03_04_071802_create_media_table.php
  backend/database/migrations/2024_03_04_072403_create_calendars_table.php
  backend/database/migrations/2024_03_04_074710_create_accommodations_table.php
  backend/database/migrations/2024_03_04_083734_create_experiences_table.php
  backend/database/migrations/2024_03_05_014548_create_reviews_table.php
Labels: Approved by: Brett, Approved by: Faith

#9 Backend - Create API to reset user password and implement email functionality
  .github/pull_request_template.md
  .github/workflows/development.yml
  backend/app/Http/Controllers/Api/V1/PasswordController.php
  backend/app/Models/User.php
  backend/app/Notifications/ResetPasswordNotification.php
  backend/resources/views/vendor/mail/html/button.blade.php
  backend/resources/views/vendor/mail/html/footer.blade.php
  backend/resources/views/vendor/mail/html/header.blade.php
  backend/resources/views/vendor/mail/html/layout.blade.php
  backend/resources/views/vendor/mail/html/message.blade.php
  backend/resources/views/vendor/mail/html/panel.blade.php
  backend/resources/views/vendor/mail/html/subcopy.blade.php
  backend/resources/views/vendor/mail/html/table.blade.php
  backend/resources/views/vendor/mail/html/themes/default.css
  backend/resources/views/vendor/mail/text/button.blade.php
  backend/resources/views/vendor/mail/text/footer.blade.php
  backend/resources/views/vendor/mail/text/header.blade.php
  backend/resources/views/vendor/mail/text/layout.blade.php
  backend/resources/views/vendor/mail/text/message.blade.php
  backend/resources/views/vendor/mail/text/panel.blade.php
  backend/resources/views/vendor/mail/text/subcopy.blade.php
  backend/resources/views/vendor/mail/text/table.blade.php
  backend/routes/api.php
Labels: Approved by: Faith

#10 implement user registration
  backend/app/Enums/UserRole.php
  backend/app/Http/Controllers/Api/V1/AuthController.php
  backend/app/Http/Requests/V1/RegistrationRequest.php
  backend/routes/api.php
Labels: Approved by: Brett

#12 Reset password
  frontend/src/app/(auth)/login/LinkSuccessModal.tsx
  frontend/src/app/(auth)/login/LoginForm.tsx
  frontend/src/app/(auth)/login/ResetPasswordModal.tsx
  frontend/src/app/(auth)/login/page.tsx
  frontend/src/app/(auth)/reset-password/ResetForm.tsx
  frontend/src/app/(auth)/reset-password/ResetSuccessModal.tsx
  frontend/src/app/(auth)/reset-password/page.tsx
  frontend/src/app/components/svgs/SuccessIcon.tsx
  frontend/src/app/interfaces/ModalProps.ts
  frontend/src/app/page.tsx
Labels: Code Review: Faith, Code Review: Cara

#14 add layouts and navigation
  frontend/src/app/(admin)/approvals/page.tsx
  frontend/src/app/(admin)/dashboard/page.tsx
  frontend/src/app/(admin)/reports/page.tsx
  frontend/src/app/(admin)/users/page.tsx
  frontend/src/app/(guest)/accommodations/new/page.tsx
  frontend/src/app/(guest)/accommodations/page.tsx
  frontend/src/app/(guest)/experiences/new/page.tsx
  frontend/src/app/(guest)/experiences/page.tsx
  frontend/src/app/(guest)/history/page.tsx
  frontend/src/app/(host)/calendar/page.tsx
  frontend/src/app/(host)/listings/page.tsx
  frontend/src/app/(shared)/profile/page.tsx
  frontend/src/app/components/Navbar.tsx
  frontend/src/app/components/NavigationItem.tsx
  frontend/src/app/components/navbar/Navbar.tsx
  frontend/src/app/components/navbar/NavbarBottom.tsx
  frontend/src/app/components/navbar/NavbarDropdown.tsx
  frontend/src/app/components/navbar/NavbarLinks.tsx
  frontend/src/app/components/svgs/Navbar/AccommodationsIcon.tsx
  frontend/src/app/components/svgs/Navbar/CalendarIcon.tsx
  frontend/src/app/components/svgs/Navbar/DashboardIcon.tsx
  frontend/src/app/components/svgs/Navbar/ExperiencesIcon.tsx
  frontend/src/app/components/svgs/Navbar/HistoryIcon.tsx
  frontend/src/app/components/svgs/Navbar/HomeIcon.tsx
  frontend/src/app/components/svgs/Navbar/ListingsIcon.tsx
  frontend/src/app/components/svgs/Navbar/LogoNavbarIcon.tsx
  frontend/src/app/components/svgs/Navbar/MenuIcon.tsx
  frontend/src/app/components/svgs/Navbar/ReportsIcon.tsx
  frontend/src/app/components/svgs/Navbar/UsersIcon.tsx
  frontend/src/app/interfaces/NavbarProps.ts
  frontend/src/app/layout.tsx
  frontend/src/app/page.tsx
  frontend/src/app/utils/enums.ts
Labels: Approved by: Brett

#15 Markup - Create components and pages related to the creation of listings (accommodation)
  frontend/.eslintrc.json
  frontend/src/app/(host)/host/new-listing/page.tsx
  frontend/src/app/components/AccommodationMoreDetails.tsx
  frontend/src/app/components/ApprovalModal.tsx
  frontend/src/app/components/Counter.tsx
  frontend/src/app/components/Listbox.tsx
  frontend/src/app/components/NewListingForm.tsx
  frontend/src/app/components/SelectType.tsx
  frontend/src/app/components/svgs/MinusIcon.tsx
  frontend/src/app/components/svgs/PlusIcon.tsx
Labels: Approved by: Brett, Approved by: John

#16 fix user registration
  backend/app/Http/Controllers/Api/V1/AuthController.php
Labels: Approved by: Brett

#17 Added User account management page and components
  frontend/src/app/(auth)/login/page.tsx
  frontend/src/app/(auth)/signup/page.tsx
  frontend/src/app/(shared)/profile/EmailField.tsx
  frontend/src/app/(shared)/profile/LegalNameField.tsx
  frontend/src/app/(shared)/profile/PasswordField.tsx
  frontend/src/app/(shared)/profile/ProfileComponent.tsx
  frontend/src/app/(shared)/profile/page.tsx
  frontend/src/app/components/ApprovalModal.tsx
  frontend/src/app/interfaces/ProfileFieldProps.ts
Labels: Approved by: Brett

#18 Update - Changed Prettier Format
  frontend/.prettierrc
Labels: Approved by: John

#19 fix page routing
  frontend/src/app/(guest)/accommodations/new/page.tsx
  frontend/src/app/(host)/listings/accommodations/[id]/page.tsx
  frontend/src/app/(host)/listings/accommodations/edit/page.tsx
  frontend/src/app/(host)/listings/accommodations/new/page.tsx
  frontend/src/app/(host)/listings/experiences/[id]/page.tsx
  frontend/src/app/(host)/listings/experiences/edit/page.tsx
  frontend/src/app/(host)/listings/experiences/new/page.tsx
  frontend/src/app/components/navbar/NavbarDropdown.tsx
Labels: Approved by: Brett, Approved by: Rian

#20 Backend - Fixed blade indentation
  backend/resources/views/vendor/mail/html/button.blade.php
  backend/resources/views/vendor/mail/html/footer.blade.php
  backend/resources/views/vendor/mail/html/header.blade.php
  backend/resources/views/vendor/mail/html/layout.blade.php
  backend/resources/views/vendor/mail/html/message.blade.php
  backend/resources/views/vendor/mail/html/panel.blade.php
  backend/resources/views/vendor/mail/html/subcopy.blade.php
  backend/resources/views/vendor/mail/html/table.blade.php
  backend/resources/views/vendor/mail/text/layout.blade.php
Labels: Approved by: Faith

#21 Backend - Create API that handles setting of availability of Listings
  backend/app/Http/Controllers/Api/V1/CalendarController.php
  backend/app/Models/Calendar.php
  backend/routes/api.php
Labels: Approved by: Cara, Approved by: Faith

#24 Markup for Listing details
  .gitignore
  frontend/public/images/ListingPic1.webp
  frontend/public/images/ListingPic2.webp
  frontend/public/images/ListingPic3.webp
  frontend/public/images/ListingPic4.webp
  frontend/public/images/ListingPic5.webp
  frontend/src/app/(host)/listings/accommodations/[id]/page.tsx
  frontend/src/app/(host)/listings/accommodations/new/page.tsx
  frontend/src/app/components/Counter.tsx
  frontend/src/app/components/accommodation/AccommodationMoreDetails.tsx
  frontend/src/app/components/accommodation/AmenityItem.tsx
  frontend/src/app/components/accommodation/AmenitySection.tsx
  frontend/src/app/components/accommodation/Counter.tsx
  frontend/src/app/components/accommodation/ListboxComponent.tsx
  frontend/src/app/components/accommodation/ListingHeader.tsx
  frontend/src/app/components/accommodation/NewListingForm.tsx
  frontend/src/app/components/accommodation/SelectType.tsx
  frontend/src/app/components/svgs/Amenities/AirconIcon.tsx
  frontend/src/app/components/svgs/Amenities/BBQGrillIcon.tsx
  frontend/src/app/components/svgs/Amenities/BackyardIcon.tsx
  frontend/src/app/components/svgs/Amenities/BalconyIcon.tsx
  frontend/src/app/components/svgs/Amenities/BathtubIcon.tsx
  frontend/src/app/components/svgs/Amenities/BeachAccessIcon.tsx
  frontend/src/app/components/svgs/Amenities/CableIcon.tsx
  frontend/src/app/components/svgs/Amenities/CribIcon.tsx
  frontend/src/app/components/svgs/Amenities/DryerIcon.tsx
  frontend/src/app/components/svgs/Amenities/FanIcon.tsx
  frontend/src/app/components/svgs/Amenities/GymIcon.tsx
  frontend/src/app/components/svgs/Amenities/HeaterIcon.tsx
  frontend/src/app/components/svgs/Amenities/IronIcon.tsx
  frontend/src/app/components/svgs/Amenities/JacuzziIcon.tsx
  frontend/src/app/components/svgs/Amenities/KitchenIcon.tsx
  frontend/src/app/components/svgs/Amenities/ParkingIcon.tsx
  frontend/src/app/components/svgs/Amenities/PetsAllowedIcon.tsx
  frontend/src/app/components/svgs/Amenities/PoolIcon.tsx
  frontend/src/app/components/svgs/Amenities/ShowerIcon.tsx
  frontend/src/app/components/svgs/Amenities/WasherIcon.tsx
  frontend/src/app/components/svgs/Amenities/WifiIcon.tsx
  frontend/src/app/interfaces/MediaType.ts
Labels: Code Review: Rian

#25 Backend - Create API for deleting Accommodation Listings
  backend/app/Http/Controllers/Api/V1/AccommodationController.php
  backend/app/Models/Accommodation.php
  backend/app/Models/Listing.php
  backend/app/Models/Media.php
Labels: Approved by: Brett, Approved by: Faith

#26 add calendar page
  frontend/src/app/(host)/calendar/page.tsx
  frontend/src/app/components/DividerText.tsx
  frontend/src/app/components/calendar/AvailabilityCalendar.tsx
  frontend/src/app/components/calendar/AvailabilitySidebar.tsx
  frontend/src/app/components/calendar/Calendar.tsx
  frontend/src/app/components/calendar/CalendarDateButton.tsx
  frontend/src/app/components/calendar/ListingsDropdown.tsx
  frontend/src/app/components/navbar/NavbarDropdown.tsx
  frontend/src/app/components/navbar/NavbarLinks.tsx
  frontend/src/app/components/svgs/Calendar/ChevronDownIcon.tsx
  frontend/src/app/components/svgs/Calendar/ChevronLeftIcon.tsx
  frontend/src/app/components/svgs/Calendar/ChevronRightIcon.tsx
  frontend/src/app/interfaces/AvailabilityCalendarProps.ts
  frontend/src/app/interfaces/AvailabilitySidebarProps.ts
  frontend/src/app/interfaces/CalendarDateButtonProps.ts
  frontend/src/app/interfaces/CalendarProps.ts
  frontend/src/app/interfaces/ListingDropdownProps.ts
  frontend/src/app/layout.tsx
  frontend/src/app/utils/constants.ts
  frontend/src/app/utils/helpers/calendar.ts
  frontend/src/app/utils/helpers/currency.ts
  frontend/src/app/utils/helpers/string.ts
  frontend/tailwind.config.ts
Labels: Approved by: John, Approved by: Rian

#27 Feature/update listing
  backend/app/Http/Controllers/Api/V1/AccommodationController.php
  backend/app/Http/Requests/V1/AccommodationRequest.php
  backend/app/Http/Requests/V1/AccommodationUpdateRequest.php
  backend/app/Models/Accommodation.php
  backend/app/Models/Listing.php
  backend/app/Models/Media.php
  backend/database/factories/BookingFactory.php
  backend/database/factories/ReasonFactory.php
  backend/database/migrations/2024_03_04_071802_create_media_table.php
  backend/routes/api.php
Labels: Approved by: Cara, Approved by: Faith

#28 change pascal to snake case
  backend/app/Http/Resources/V1/AdminResource.php
  backend/app/Http/Resources/V1/UserResource.php
Labels: Approved by: John, Approved by: Rian

#29 Allow return of empty array for calendar
  backend/app/Http/Controllers/Api/V1/CalendarController.php
Labels: Approved by: Faith

#30 Backend - Create API to update user info
  backend/app/Http/Controllers/Api/V1/AccommodationController.php
  backend/app/Http/Controllers/Api/V1/UserController.php
  backend/app/Http/Requests/V1/AccommodationRequest.php
  backend/app/Http/Requests/V1/AccommodationUpdateRequest.php
  backend/app/Http/Requests/V1/UserUpdateRequest.php
  backend/app/Models/Listing.php
  backend/app/Models/User.php
  backend/database/migrations/2024_03_04_070040_create_listings_table.php
  backend/routes/api.php
Labels: Approved by: Brett, Approved by: Faith

#32 Integrate signup, login, logout, and middleware
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/(auth)/login/LoginForm.tsx
  frontend/src/app/(auth)/signup/SignUpComponent.tsx
  frontend/src/app/(auth)/signup/SignUpForm.tsx
  frontend/src/app/(auth)/signup/page.tsx
  frontend/src/app/components/EditListingForm.tsx
  frontend/src/app/components/accommodation/ListingHeader.tsx
  frontend/src/app/components/accommodation/NewListingForm.tsx
  frontend/src/app/components/navbar/Navbar.tsx
  frontend/src/app/components/navbar/NavbarDropdown.tsx
  frontend/src/app/interfaces/MediaType.ts
  frontend/src/app/interfaces/types.ts
  frontend/src/app/utils/helpers/getInitials.ts
  frontend/src/app/utils/helpers/userHelper.ts
  frontend/src/middleware.ts
Labels: Code Review: Faith, Code Review: Rian

#35 Integration - Call API from FE to delete Listings
  frontend/src/app/(host)/listings/accommodations/edit/[id]/page.tsx
  frontend/src/app/components/DeleteModal.tsx
  frontend/src/app/components/EditListingForm.tsx
  frontend/src/app/utils/helpers/listingHelper.ts
Labels: Code Review: John

#36 Feature/add new listing
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/(auth)/signup/SignUpForm.tsx
  frontend/src/app/(host)/listings/accommodations/new/page.tsx
  frontend/src/app/api/uploadthing/core.ts
  frontend/src/app/api/uploadthing/route.ts
  frontend/src/app/components/accommodation/AccommodationMoreDetails.tsx
  frontend/src/app/components/accommodation/Counter.tsx
  frontend/src/app/components/accommodation/ImageCollection.tsx
  frontend/src/app/components/accommodation/ListboxComponent.tsx
  frontend/src/app/components/accommodation/NewListingForm.tsx
  frontend/src/app/components/accommodation/SelectType.tsx
  frontend/src/app/components/uploadthing/UploadDropzone.tsx
  frontend/src/app/config/config.ts
  frontend/src/app/interfaces/AccomodationData.ts
  frontend/src/app/utils/helpers/accommodationHelper.ts
  frontend/src/app/utils/uploadthing/uploadthing.ts
Labels: Code Review: John, Code Review: Rian

#37 update google login endpoint
  backend/app/Exceptions/Handler.php
  backend/app/Http/Controllers/Api/V1/AdminAuthController.php
  backend/app/Http/Controllers/Api/V1/AuthController.php
  backend/app/Http/Controllers/Api/V1/GoogleAuthController.php
  backend/app/Http/Requests/V1/GoogleLoginRequest.php
  backend/app/Http/Requests/V1/GoogleRegistrationRequest.php
  backend/app/Models/Admin.php
  backend/app/Models/User.php
  backend/routes/api.php
Labels: Approved by: Cara, Approved by: John

#38 Feature/integration update listing
  frontend/src/app/(host)/listings/accommodations/edit/[id]/EditListingComponent.tsx
  frontend/src/app/(host)/listings/accommodations/edit/[id]/page.tsx
  frontend/src/app/components/EditListingForm.tsx
  frontend/src/app/components/accommodation/ImageCollectionUpdate.tsx
  frontend/src/app/components/accommodation/ListingHeader.tsx
  frontend/src/app/components/uploadthing/UploadAccommodationUpdate.tsx
  frontend/src/app/interfaces/AccomodationData.ts
  frontend/src/app/utils/helpers/accommodationHelper.ts
  frontend/src/app/utils/helpers/listingHelper.ts
  package-lock.json
Labels: Code Review: John, Code Review: Rian

#39 OAuth Implementation and Login Modification
  frontend/next.config.mjs
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/(auth)/login/LoginComponent.tsx
  frontend/src/app/(auth)/login/LoginForm.tsx
  frontend/src/app/(auth)/login/page.tsx
  frontend/src/app/(auth)/reset-password/page.tsx
  frontend/src/app/(auth)/role-selection/page.tsx
  frontend/src/app/(auth)/signup/RadioCard.tsx
  frontend/src/app/(auth)/signup/SignUpComponent.tsx
  frontend/src/app/(auth)/signup/SignUpForm.tsx
  frontend/src/app/(auth)/signup/page.tsx
  frontend/src/app/(shared)/profile/ProfileComponent.tsx
  frontend/src/app/api/auth/[...nextauth]/nextAuthOptions.ts
  frontend/src/app/api/auth/[...nextauth]/route.ts
  frontend/src/app/components/GoogleButton.tsx
  frontend/src/app/components/RadioCard.tsx
  frontend/src/app/components/RoleSelectForm.tsx
  frontend/src/app/components/RoleSelectModal.tsx
  frontend/src/app/components/svgs/WarnIcon.tsx
  frontend/src/app/utils/helpers/userHelper.ts
Labels: Approved by: Cara, Approved by: Faith

#40 Integration - Call API from FE to update User Info
  frontend/src/app/(shared)/profile/EmailField.tsx
  frontend/src/app/(shared)/profile/LegalNameField.tsx
  frontend/src/app/(shared)/profile/PasswordField.tsx
  frontend/src/app/(shared)/profile/ProfileComponent.tsx
  frontend/src/app/(shared)/profile/page.tsx
  frontend/src/app/interfaces/ProfileFieldProps.ts
  frontend/src/app/interfaces/types.ts
  frontend/src/app/utils/helpers/userHelper.ts
Labels: Approved by: Faith, Approved by: John

#41 Changes involved with JWT containing user details
  backend/app/Claims/UserClaim.php
  backend/app/Http/Controllers/Api/V1/AdminAuthController.php
  backend/app/Http/Controllers/Api/V1/AuthController.php
  backend/app/Http/Controllers/Api/V1/GoogleAuthController.php
  backend/app/Models/User.php
  backend/composer.json
  backend/composer.lock
  backend/config/passport-claims.php
  frontend/src/app/(shared)/profile/EmailField.tsx
  frontend/src/app/(shared)/profile/LegalNameField.tsx
  frontend/src/app/(shared)/profile/PasswordField.tsx
  frontend/src/app/(shared)/profile/page.tsx
  frontend/src/app/api/auth/[...nextauth]/nextAuthOptions.ts
  frontend/src/app/interfaces/ProfileFieldProps.ts
  frontend/src/app/interfaces/types.ts
  frontend/src/app/utils/helpers/userHelper.ts
  frontend/src/middleware.ts
Labels: Approved by: Faith

#43 Update/fixes and enhancements
  frontend/src/app/(auth)/login/ResetPasswordModal.tsx
  frontend/src/app/(auth)/reset-password/ResetForm.tsx
  frontend/src/app/(host)/calendar/page.tsx
  frontend/src/app/(host)/listings/AddressForm.tsx
  frontend/src/app/(host)/listings/PriceForm.tsx
  frontend/src/app/(host)/listings/accommodations/DetailForm.tsx
  frontend/src/app/(host)/listings/accommodations/[id]/edit/ImageCollectionUpdate.tsx
  frontend/src/app/(host)/listings/accommodations/[id]/page.tsx
  frontend/src/app/(host)/listings/accommodations/new/ImageCollection.tsx
  frontend/src/app/(host)/listings/accommodations/new/NewListingForm.tsx
  frontend/src/app/(host)/listings/page.tsx
  frontend/src/app/(shared)/profile/LegalNameField.tsx
  frontend/src/app/(shared)/profile/PasswordField.tsx
  frontend/src/app/(shared)/profile/ProfileComponent.tsx
  frontend/src/app/components/accommodation/AccommodationListComponent.tsx
  frontend/src/app/components/accommodation/AccommodationTypeItem.tsx
  frontend/src/app/components/accommodation/ListingUploader.tsx
  frontend/src/app/components/calendar/AvailabilityCalendar.tsx
  frontend/src/app/components/calendar/AvailabilitySidebar.tsx
  frontend/src/app/components/calendar/Calendar.tsx
  frontend/src/app/components/calendar/ListingsDropdown.tsx
  frontend/src/app/components/listings/HostListingItem.tsx
  frontend/src/app/components/listings/HostListings.tsx
  frontend/src/app/components/listings/ListingHeader.tsx
  frontend/src/app/components/listings/ListingItem.tsx
  frontend/src/app/components/svgs/Accommodation Types/BeachHouseIcon.tsx
  frontend/src/app/components/svgs/Accommodation Types/CabinIcon.tsx
  frontend/src/app/components/svgs/Accommodation Types/CondominiumIcon.tsx
  frontend/src/app/components/svgs/Accommodation Types/FarmIcon.tsx
  frontend/src/app/components/svgs/Accommodation Types/HotelIcon.tsx
  frontend/src/app/components/svgs/Accommodation Types/MansionIcon.tsx
  frontend/src/app/components/svgs/Accommodation Types/OthersIcon.tsx
  frontend/src/app/components/svgs/Accommodation Types/RoomIcon.tsx
  frontend/src/app/components/svgs/Accommodation Types/TinyHouseIcon.tsx
  frontend/src/app/components/svgs/Accommodation Types/TowerIcon.tsx
  frontend/src/app/components/svgs/Listings/AddIcon.tsx
  frontend/src/app/interfaces/HostListingsProps.tsx
  frontend/src/app/interfaces/types.ts
  frontend/src/app/layout.tsx
  frontend/src/app/page.tsx
  frontend/src/app/utils/helpers/accommodation/request.ts
  frontend/src/app/utils/helpers/accommodation/validation.ts
  frontend/src/app/utils/helpers/availability/calendar.ts
  frontend/src/app/utils/helpers/availability/requests.ts
Labels: Approved by: Cara, Approved by: Faith, Approved by: Rian

#44 Removed unnecessary console logs.
  frontend/src/app/(auth)/login/LoginForm.tsx
  frontend/src/app/(host)/listings/accommodations/[id]/edit/EditListingForm.tsx
  frontend/src/app/api/auth/[...nextauth]/nextAuthOptions.ts
  frontend/src/app/utils/helpers/accommodation/request.ts
  frontend/src/app/utils/helpers/userHelper.ts
Labels: Code Review: Brett, Code Review: John

#45 Backend - Refactored and clean code for Accommodation Management
  backend/app/Http/Controllers/Api/V1/AccommodationController.php
  backend/app/Models/Accommodation.php
  backend/app/Models/Listing.php
  backend/app/Models/Media.php
Labels: Approved by: Brett, Approved by: Faith

#46 Update/calendar refactor
  backend/app/Http/Controllers/Api/V1/CalendarController.php
  backend/app/Http/Requests/V1/CalendarRequest.php
  backend/app/Models/Listing.php
Labels: Approved by: Cara, Approved by: Faith

#47 Update/redirect after create listing
  frontend/src/app/(host)/listings/accommodations/new/page.tsx
  frontend/src/app/components/ApprovalModal.tsx
  frontend/src/app/utils/helpers/accommodation/request.ts
Labels: Code Review: John, Code Review: Rian

#49 Feature/create review
  backend/app/Http/Controllers/Api/V1/ReviewController.php
  backend/app/Http/Requests/V1/ReviewRequest.php
  backend/app/Models/Review.php
  backend/routes/api.php
Labels: Code Review: Faith, Approved by: Cara

#50 Added components for displaying reviews in listing details page.
  frontend/src/app/(host)/listings/accommodations/[id]/page.tsx
  frontend/src/app/api/auth/[...nextauth]/route.ts
  frontend/src/app/components/accommodation/AmenityItem.tsx
  frontend/src/app/components/accommodation/AmenitySection.tsx
  frontend/src/app/components/navbar/NavbarBottom.tsx
  frontend/src/app/components/navbar/NavbarDropdown.tsx
  frontend/src/app/components/review/ReviewComponent.tsx
  frontend/src/app/components/review/ReviewHeader.tsx
  frontend/src/app/components/review/ReviewPaginate.tsx
  frontend/src/app/components/review/ReviewSection.tsx
  frontend/src/app/components/review/StarsComponent.tsx
  frontend/src/app/components/svgs/Amenities/AirconIcon.tsx
  frontend/src/app/components/svgs/Amenities/CribIcon.tsx
  frontend/src/app/components/svgs/Amenities/WasherIcon.tsx
  frontend/src/app/components/svgs/Review/CleanlinessIcon.tsx
  frontend/src/app/components/svgs/Review/FilledStarIcon.tsx
  frontend/src/app/components/svgs/Review/LocationIcon.tsx
  frontend/src/app/components/svgs/Review/StarIcon.tsx
  frontend/src/app/components/svgs/Review/ValueIcon.tsx
  frontend/src/app/interfaces/types.ts
Labels: Approved by: Faith, Approved by: Rian

#52 Created Add review modal
  frontend/src/app/components/review/AddReviewForm.tsx
  frontend/src/app/components/review/AddReviewModal.tsx
  frontend/src/app/components/review/StarsAddReview.tsx
  frontend/src/app/components/svgs/Review/CleanlinessSmallIcon.tsx
  frontend/src/app/components/svgs/Review/LocationSmallIcon.tsx
  frontend/src/app/components/svgs/Review/ValueSmallIcon.tsx
Labels: Approved by: Faith, Approved by: Rian

#53 Created middleware to restrict access to certain routes
  backend/app/Http/Kernel.php
  backend/app/Http/Middleware/CheckOwnership.php
  backend/app/Http/Middleware/CheckUserRole.php
  backend/routes/api.php
  package-lock.json
Labels: Approved by: Cara, Approved by: Faith

#54 Markup - Create components and pages for experiences (Create, Update, Delete)
  frontend/src/app/(host)/listings/accommodations/[id]/edit/EditListingComponent.tsx
  frontend/src/app/(host)/listings/accommodations/[id]/edit/EditListingForm.tsx
  frontend/src/app/(host)/listings/experiences/edit/EditExperienceForm.tsx
  frontend/src/app/(host)/listings/experiences/edit/page.tsx
  frontend/src/app/(host)/listings/experiences/new/ExperienceMoreDetails.tsx
  frontend/src/app/(host)/listings/experiences/new/NewExperienceForm.tsx
  frontend/src/app/(host)/listings/experiences/new/page.tsx
  frontend/src/app/components/DeleteModal.tsx
  frontend/src/app/components/experiences/ExperienceApprovalModal.tsx
  frontend/src/app/components/experiences/InclusionsListbox.tsx
  frontend/src/app/components/experiences/LanguagesListbox.tsx
  frontend/src/app/components/experiences/Slider.tsx
  frontend/src/app/utils/enums.ts
Labels: Approved by: Brett, Approved by: John

#55 add booking accommodation and experience endpoint
  backend/app/Http/Controllers/Api/V1/AuthController.php
  backend/app/Http/Controllers/Api/V1/BookingController.php
  backend/app/Http/Controllers/Api/V1/CalendarController.php
  backend/app/Http/Controllers/Api/V1/GoogleAuthController.php
  backend/app/Http/Requests/V1/BookingRequest.php
  backend/app/Models/Booking.php
  backend/app/Models/Calendar.php
  backend/app/Models/Listing.php
  backend/app/Models/User.php
  backend/app/Rules/DateAvailabilityRule.php
  backend/app/Rules/MinMaxDaysRule.php
  backend/app/Rules/MinMaxGuestsRule.php
  backend/database/migrations/2024_03_20_062759_add_booking_id_to_calendars.php
  backend/routes/api.php
Labels: Approved by: Brett, Approved by: Cara

#56 Experience details page
  frontend/next.config.mjs
  frontend/src/app/(host)/listings/experiences/[id]/page.tsx
  frontend/src/app/(host)/listings/experiences/edit/EditExperienceForm.tsx
  frontend/src/app/(host)/listings/experiences/new/page.tsx
  frontend/src/app/components/experience/ExperienceHeader.tsx
  frontend/src/app/components/experience/InclusionItem.tsx
  frontend/src/app/components/experience/InclusionSection.tsx
  frontend/src/app/components/experiences/ExperienceApprovalModal.tsx
  frontend/src/app/components/experiences/InclusionsListbox.tsx
  frontend/src/app/components/experiences/LanguagesListbox.tsx
  frontend/src/app/components/navbar/NavbarBottom.tsx
  frontend/src/app/components/svgs/Inclusions/TransportIcon.tsx
  frontend/src/app/components/svgs/Report/FlagIcon.tsx
  frontend/src/app/interfaces/types.ts
  frontend/src/app/utils/enums.ts
  frontend/src/middleware.ts
Labels: Code Review: Faith, Code Review: Rian, For Code Review

#57 Backend - Create API for searching and filtering accommodations and experiences
  backend/app/Http/Controllers/Api/V1/AccommodationController.php
  backend/app/Http/Controllers/Api/V1/ExperienceController.php
  backend/app/Http/Controllers/Api/V1/ListingController.php
  backend/app/Http/Requests/V1/ExperienceRequest.php
  backend/app/Http/Requests/V1/ExperienceUpdateRequest.php
  backend/app/Models/Accommodation.php
  backend/app/Models/Experience.php
  backend/app/Models/Listing.php
  backend/database/migrations/2024_03_04_073957_create_inclusions_table.php
  backend/database/migrations/2024_03_04_083734_create_experiences_table.php
  backend/routes/api.php
Labels: Approved by: Faith

#58 update listings api calls
  frontend/src/app/components/calendar/ListingsDropdown.tsx
  frontend/src/app/utils/helpers/accommodation/request.ts
  frontend/src/app/utils/helpers/availability/requests.ts
Labels: Approved by: John, Approved by: Rian

#59 Feature/integration review
  frontend/src/app/(host)/listings/experiences/[id]/page.tsx
  frontend/src/app/components/review/AddReviewForm.tsx
  frontend/src/app/components/review/AddReviewModal.tsx
  frontend/src/app/components/review/ReviewComponent.tsx
  frontend/src/app/components/review/ReviewSection.tsx
  frontend/src/app/components/review/StarsAddReview.tsx
  frontend/src/app/interfaces/types.ts
  frontend/src/app/utils/helpers/review/request.ts
  frontend/src/app/utils/helpers/review/validation.ts
Labels: Code Review: John, Code Review: Rian

#60 Markup - Create components and pages for managing bookings and bookings history
  frontend/src/app/(guest)/history/page.tsx
  frontend/src/app/components/BookingHistory.tsx
  frontend/src/app/components/BookingStatus.tsx
Labels: Approved by: Brett, Approved by: John

#61 Backend - Create API for managing bookings of a guest
  backend/app/Http/Controllers/Api/V1/BookingController.php
  backend/app/Http/Controllers/Api/V1/ListingController.php
  backend/app/Http/Middleware/CheckOwnership.php
  backend/app/Models/Booking.php
  backend/app/Models/Calendar.php
  backend/app/Models/Listing.php
  backend/app/Models/User.php
  backend/routes/api.php
Labels: Approved by: Brett, Approved by: Faith

#62 Feature/integration display listing and review
  frontend/src/app/(host)/listings/accommodations/[id]/page.tsx
  frontend/src/app/(host)/listings/experiences/[id]/edit/EditExperienceForm.tsx
  frontend/src/app/(host)/listings/experiences/[id]/edit/page.tsx
  frontend/src/app/(host)/listings/experiences/[id]/page.tsx
  frontend/src/app/components/ToEditButton.tsx
  frontend/src/app/components/accommodation/ListingHeader.tsx
  frontend/src/app/components/experience/ExperienceHeader.tsx
  frontend/src/app/components/review/ReviewComponent.tsx
  frontend/src/app/components/review/ReviewHeader.tsx
  frontend/src/app/components/review/ReviewSection.tsx
  frontend/src/app/utils/date.ts
  frontend/src/app/utils/helpers/experience/request.ts
  frontend/src/app/utils/helpers/review/calculate.ts
  frontend/src/app/utils/helpers/userHelper.ts
Labels: Approved by: John, Approved by: Rian

#63 Request/error message component
  frontend/src/app/(auth)/login/LoginForm.tsx
  frontend/src/app/(auth)/login/ResetPasswordModal.tsx
  frontend/src/app/(auth)/reset-password/ResetForm.tsx
  frontend/src/app/(host)/listings/PriceForm.tsx
  frontend/src/app/(host)/listings/accommodations/[id]/edit/EditListingForm.tsx
  frontend/src/app/(host)/listings/accommodations/new/NewListingForm.tsx
  frontend/src/app/components/ErrorMessage.tsx
  frontend/src/app/components/review/AddReviewForm.tsx
Labels: Code Review: John, Approved by: Rian

#65 Request/modal delete fix
  frontend/src/app/(host)/listings/accommodations/[id]/edit/EditListingComponent.tsx
  frontend/src/app/components/DeleteModal.tsx
  frontend/src/app/utils/helpers/accommodation/request.ts
Labels: Approved by: John, Approved by: Rian

#66 Task/split reviews
  backend/app/Http/Controllers/Api/V1/ReviewController.php
  backend/app/Http/Requests/V1/AccommodationReviewRequest.php
  backend/app/Http/Requests/V1/ExperienceReviewRequest.php
  backend/app/Models/Review.php
  backend/database/migrations/2024_03_05_014548_create_reviews_table.php
  backend/routes/api.php
Labels: Approved by: Cara

#69 Backend - Create API for searching and filtering accommodations and experiences (host)
  backend/app/Http/Controllers/Api/V1/ListingController.php
  backend/app/Models/Listing.php
  backend/routes/api.php
Labels: Approved by: Faith

#64 add search and filter accommodation
  frontend/src/app/(guest)/accommodations/page.tsx
  frontend/src/app/(host)/listings/page.tsx
  frontend/src/app/components/accommodation/AccommodationTypeItem.tsx
  frontend/src/app/components/accommodation/AccommodationTypes.tsx
  frontend/src/app/components/listings/GuestListingHeader.tsx
  frontend/src/app/components/listings/GuestListingItem.tsx
  frontend/src/app/components/listings/GuestListings.tsx
  frontend/src/app/components/listings/HostListings.tsx
  frontend/src/app/components/listings/ListingPagination.tsx
  frontend/src/app/components/listings/ListingSearchBar.tsx
  frontend/src/app/interfaces/ListingsProps.tsx
  frontend/src/app/interfaces/types.ts
  frontend/src/app/utils/helpers/accommodation/request.ts
Labels: Approved by: Cara, Approved by: John, Approved by: Rian

#70 Backend - Create API for managing bookings of a guest (host)
  backend/app/Enums/BookingStatus.php
  backend/app/Http/Controllers/Api/V1/BookingController.php
  backend/app/Http/Middleware/CheckOwnership.php
  backend/app/Http/Middleware/CheckUserRole.php
  backend/app/Models/Admin.php
  backend/app/Models/Booking.php
  backend/app/Models/Listing.php
  backend/app/Models/User.php
  backend/database/migrations/2024_03_04_071150_create_bookings_table.php
  backend/routes/api.php
Labels: Approved by: Brett, Approved by: Faith

#72 Update/review markup integration
  backend/app/Models/Review.php
  frontend/src/app/(guest)/accommodations/[id]/page.tsx
  frontend/src/app/(guest)/experiences/[id]/page.tsx
  frontend/src/app/(host)/listings/accommodations/[id]/page.tsx
  frontend/src/app/(host)/listings/experiences/[id]/edit/EditExperienceComponent.tsx
  frontend/src/app/(host)/listings/experiences/[id]/page.tsx
  frontend/src/app/components/review/AccommodationReviewForm.tsx
  frontend/src/app/components/review/AddReviewModal.tsx
  frontend/src/app/components/review/ExperienceReviewForm.tsx
  frontend/src/app/components/review/ReviewHeader.tsx
  frontend/src/app/components/review/ReviewSection.tsx
  frontend/src/app/components/review/ReviewSuccessModal.tsx
  frontend/src/app/components/review/StarsAccommodationReview.tsx
  frontend/src/app/components/review/StarsExperienceReview.tsx
  frontend/src/app/interfaces/types.ts
  frontend/src/app/utils/helpers/review/request.ts
  frontend/src/app/utils/helpers/review/validation.ts
Labels: Approved by: John, Approved by: Rian

#71 Markup for guest booking management
  frontend/src/app/(guest)/accommodations/[id]/page.tsx
  frontend/src/app/components/StatusChip.tsx
  frontend/src/app/components/home/host/BookingActions.tsx
  frontend/src/app/components/home/host/HostDashboard.tsx
  frontend/src/app/components/home/host/ListingBookingsTable.tsx
  frontend/src/app/components/home/host/PendingCardsSlicer.tsx
  frontend/src/app/components/home/host/PendingListingCard.tsx
  frontend/src/app/components/svgs/Booking/AcceptIcon.tsx
  frontend/src/app/components/svgs/Booking/RejectIcon.tsx
  frontend/src/app/components/svgs/TrashIcon.tsx
  frontend/src/app/components/svgs/WatchIconSm.tsx
  frontend/src/app/interfaces/types.ts
  frontend/src/app/page.tsx
  frontend/src/app/utils/enums.ts
  frontend/src/app/utils/helpers/accommodation/request.ts
Labels: Code Review: Brett, Code Review: Rian, For Code Review

#74 Update listing to display newest to oldest
  backend/app/Models/Listing.php
  backend/routes/api.php
Labels: Approved by: Brett

#73 add filter and search host listings
  frontend/src/app/(auth)/login/page.tsx
  frontend/src/app/(guest)/accommodations/page.tsx
  frontend/src/app/(host)/listings/page.tsx
  frontend/src/app/components/listings/AddNewListingButton.tsx
  frontend/src/app/components/listings/EmptyListing.tsx
  frontend/src/app/components/listings/GuestListingHeader.tsx
  frontend/src/app/components/listings/GuestListingItem.tsx
  frontend/src/app/components/listings/GuestListings.tsx
  frontend/src/app/components/listings/HostListingHeader.tsx
  frontend/src/app/components/listings/HostListingItem.tsx
  frontend/src/app/components/listings/HostListings.tsx
  frontend/src/app/components/listings/ListingHeader.tsx
  frontend/src/app/components/listings/ListingItem.tsx
  frontend/src/app/components/listings/ListingPagination.tsx
  frontend/src/app/components/listings/ListingSearchBar.tsx
  frontend/src/app/components/listings/Listings.tsx
  frontend/src/app/interfaces/ListingsProps.tsx
  frontend/src/app/interfaces/types.ts
  frontend/src/app/utils/enums.ts
  frontend/src/app/utils/helpers/accommodation/request.ts
  frontend/src/app/utils/helpers/experience/request.ts
Labels: Approved by: John, Approved by: Rian

#75 allow booking for active listings only
  backend/app/Models/Booking.php
Labels: Approved by: Cara

#76 add search and filter experiences
  frontend/src/app/(guest)/experiences/page.tsx
  frontend/src/app/components/accommodation/AccommodationTypeItem.tsx
  frontend/src/app/components/experience/ExperienceTypeItem.tsx
  frontend/src/app/components/experience/ExperienceTypes.tsx
  frontend/src/app/components/listings/AddNewListingButton.tsx
  frontend/src/app/components/listings/ListingHeader.tsx
  frontend/src/app/components/listings/ListingItem.tsx
  frontend/src/app/components/listings/ListingSearchBar.tsx
  frontend/src/app/layout.tsx
  frontend/src/app/utils/helpers/experience/request.ts
Labels: Approved by: John, Approved by: Rian
