Repository framgia/sph_sunbnb_sim, pull requests merged in 2024-04, with the labels that each got.

#77 Checkout for accommodation and experiences integration
  frontend/src/app/(guest)/accommodations/[id]/checkout/page.tsx
  frontend/src/app/(guest)/accommodations/[id]/page.tsx
  frontend/src/app/(guest)/experiences/[id]/checkout/page.tsx
  frontend/src/app/(guest)/experiences/[id]/page.tsx
  frontend/src/app/components/booking/AccommodationBookingConfirm.tsx
  frontend/src/app/components/booking/AccommodationBookingSticky.tsx
  frontend/src/app/components/booking/ExperienceBookingConfirm.tsx
  frontend/src/app/components/booking/ExperienceBookingSticky.tsx
  frontend/src/app/components/booking/ThankYouModal.tsx
  frontend/src/app/components/experience/ExperienceHeader.tsx
  frontend/src/app/components/listings/ListingHeader.tsx
  frontend/src/app/interfaces/types.ts
  frontend/src/app/layout.tsx
  frontend/src/app/page.tsx
  frontend/src/app/utils/helpers/booking/DateHelper.ts
  frontend/src/app/utils/helpers/booking/request.ts
Labels: Code Review: Faith, Code Review: Rian, For Code Review

#78 Backend - Add reviewed attribute to booking and update it on review
  backend/app/Http/Controllers/Api/V1/BookingController.php
  backend/app/Models/Booking.php
  backend/database/migrations/2024_04_01_020514_update_bookings_table.php
  backend/routes/api.php
Labels: Approved by: Brett

#80 update restrictions on booking dates
  backend/app/Http/Requests/V1/BookingRequest.php
  backend/app/Rules/MinMaxDaysRule.php
Labels: Approved by: Brett, Approved by: Cara

#81 Feature/integration booking host management
  backend/app/Models/Booking.php
  backend/app/Models/Listing.php
  frontend/src/app/components/StatusChip.tsx
  frontend/src/app/components/home/host/BookingActions.tsx
  frontend/src/app/components/home/host/HostDashboard.tsx
  frontend/src/app/components/home/host/ListingBookingsTable.tsx
  frontend/src/app/components/home/host/PendingCardsSlicer.tsx
  frontend/src/app/components/home/host/PendingListModal.tsx
  frontend/src/app/components/home/host/PendingListingCard.tsx
  frontend/src/app/components/review/AccommodationReviewForm.tsx
  frontend/src/app/components/review/ExperienceReviewForm.tsx
  frontend/src/app/interfaces/types.ts
  frontend/src/app/utils/helpers/booking/request.ts
  frontend/src/app/utils/helpers/bookingmanagement/request.ts
  frontend/src/app/utils/helpers/experience/request.ts
  frontend/src/app/utils/helpers/getListingType.ts
  frontend/src/app/utils/helpers/review/request.ts
Labels: Approved by: Cara, Approved by: John, Approved by: Rian

#82 Delete option after review + bug fixes
  frontend/src/app/(guest)/accommodations/[id]/page.tsx
  frontend/src/app/(guest)/experiences/[id]/page.tsx
  frontend/src/app/(host)/listings/accommodations/[id]/page.tsx
  frontend/src/app/(host)/listings/experiences/[id]/page.tsx
  frontend/src/app/components/BookingStatus.tsx
  frontend/src/app/components/StatusChip.tsx
  frontend/src/app/components/accommodation/ListingHeader.tsx
  frontend/src/app/components/experience/ExperienceHeader.tsx
  frontend/src/app/components/home/host/ListingBookingsTable.tsx
  frontend/src/app/components/listings/ListingItem.tsx
  frontend/src/app/page.tsx
  frontend/src/app/utils/helpers/bookinghistory/request.ts
  frontend/src/app/utils/helpers/experience/request.ts
  frontend/src/app/utils/helpers/review/request.ts
Labels: Approved by: Brett, Approved by: Rian

#83 update calendar listing availability
  frontend/src/app/components/calendar/AvailabilityCalendar.tsx
  frontend/src/app/components/calendar/AvailabilitySidebar.tsx
  frontend/src/app/components/calendar/Calendar.tsx
  frontend/src/app/components/calendar/CalendarDateButton.tsx
  frontend/src/app/components/calendar/ListingsDropdown.tsx
  frontend/src/app/components/listings/ListingHeader.tsx
  frontend/src/app/components/listings/ListingSearchBar.tsx
  frontend/src/app/interfaces/AvailabilityCalendarProps.ts
  frontend/src/app/interfaces/AvailabilitySidebarProps.ts
  frontend/src/app/interfaces/CalendarDateButtonProps.ts
  frontend/src/app/interfaces/CalendarProps.ts
  frontend/src/app/interfaces/ListingDropdownProps.ts
  frontend/src/app/interfaces/ListingsProps.tsx
  frontend/src/app/interfaces/types.ts
  frontend/src/app/layout.tsx
  frontend/src/app/utils/date.ts
Labels: Approved by: John, Approved by: Rian

#84 Allow decimal for price input in create/edit listings
  frontend/src/app/(guest)/experiences/[id]/page.tsx
  frontend/src/app/(host)/listings/PriceForm.tsx
  frontend/src/app/(host)/listings/accommodations/[id]/page.tsx
  frontend/src/app/(host)/listings/experiences/[id]/page.tsx
  frontend/src/app/components/accommodation/ListingHeader.tsx
  frontend/src/app/components/booking/DefaultSticky.tsx
  frontend/src/app/components/experience/ExperienceHeader.tsx
  frontend/src/app/components/experience/ExperiencePriceForm.tsx
Labels: Approved by: Brett, Approved by: John

#86 Remove duplicate types
  frontend/src/app/(guest)/experiences/[id]/page.tsx
  frontend/src/app/(guest)/history/BookingHistoryComponent.tsx
  frontend/src/app/(host)/listings/experiences/[id]/page.tsx
  frontend/src/app/components/booking/AccommodationBookingConfirm.tsx
  frontend/src/app/components/booking/ExperienceBookingConfirm.tsx
  frontend/src/app/components/home/host/BookingActions.tsx
  frontend/src/app/components/home/host/ListingBookingsTable.tsx
  frontend/src/app/components/home/host/PendingListModal.tsx
  frontend/src/app/interfaces/types.ts
  frontend/src/app/utils/helpers/accommodation/request.ts
  frontend/src/app/utils/helpers/experience/request.ts
Labels: Approved by: John

#85 Host listings separation
  frontend/src/app/(guest)/experiences/[id]/page.tsx
  frontend/src/app/(host)/listings/accommodations/[id]/page.tsx
  frontend/src/app/(host)/listings/accommodations/new/NewListingForm.tsx
  frontend/src/app/(host)/listings/experiences/[id]/page.tsx
  frontend/src/app/(host)/listings/experiences/new/NewExperienceForm.tsx
  frontend/src/app/components/accommodation/ListingHeader.tsx
  frontend/src/app/components/booking/AccommodationBookingSticky.tsx
  frontend/src/app/components/booking/ExperienceBookingSticky.tsx
  frontend/src/app/components/home/host/PendingListingCard.tsx
  frontend/src/app/components/review/ReviewComponent.tsx
  frontend/src/app/components/review/ReviewHeader.tsx
  frontend/src/app/components/svgs/Review/CleanlinessIcon.tsx
  frontend/src/app/components/svgs/Review/FilledStarIcon.tsx
  frontend/src/app/components/svgs/Review/LocationIcon.tsx
  frontend/src/app/components/svgs/Review/StarIcon.tsx
  frontend/src/app/components/svgs/Review/ValueIcon.tsx
Labels: Approved by: Brett, Approved by: Faith

#87 View full comment
  frontend/src/app/(guest)/accommodations/[id]/page.tsx
  frontend/src/app/(host)/listings/accommodations/[id]/edit/EditListingComponent.tsx
  frontend/src/app/components/experience/ExperienceAddressForm.tsx
  frontend/src/app/components/experience/ExperienceCounter.tsx
  frontend/src/app/components/home/host/ListingBookingsTable.tsx
  frontend/src/app/components/review/ReviewComponent.tsx
  frontend/src/app/components/review/ReviewPaginate.tsx
  frontend/src/app/components/review/ReviewSection.tsx
  frontend/src/app/components/review/ShowReviewModal.tsx
  frontend/src/app/interfaces/types.ts
  frontend/src/app/utils/helpers/availability/requests.ts
  frontend/src/app/utils/helpers/review/request.ts
Labels: Approved by: John

#89 Fix review header
  backend/app/Models/Review.php
  frontend/src/app/components/review/ReviewHeader.tsx
  frontend/src/app/components/review/ReviewSection.tsx
  frontend/src/app/utils/helpers/review/request.ts
Labels: Code Review: John

#90 update history page
  frontend/src/app/(guest)/history/BookingHistoryComponent.tsx
  frontend/src/app/(guest)/history/BookingHistoryData.tsx
  frontend/src/app/components/BookingStatus.tsx
  frontend/src/app/components/navbar/Navbar.tsx
  frontend/src/app/components/navbar/NavbarDropdown.tsx
  frontend/src/app/components/navbar/NavbarLinks.tsx
Labels: Approved by: John, Approved by: Rian

#91 Request/remove comments logs
  frontend/src/app/(auth)/login/LoginForm.tsx
  frontend/src/app/(guest)/experiences/[id]/page.tsx
  frontend/src/app/(shared)/profile/EmailField.tsx
  frontend/src/app/(shared)/profile/LegalNameField.tsx
  frontend/src/app/(shared)/profile/PasswordField.tsx
  frontend/src/app/components/listings/ListingSearchBar.tsx
  frontend/src/app/interfaces/types.ts
  frontend/src/app/utils/helpers/bookingmanagement/request.ts
  frontend/src/middleware.ts
Labels: Approved by: John, Approved by: Rian

#92 UI Margin changes
  frontend/src/app/(host)/listings/accommodations/[id]/edit/EditListingForm.tsx
  frontend/src/app/(host)/listings/accommodations/new/NewListingForm.tsx
  frontend/src/app/(host)/listings/experiences/[id]/edit/EditExperienceForm.tsx
  frontend/src/app/(host)/listings/experiences/new/NewExperienceForm.tsx
  frontend/src/app/components/accommodation/ListingUploader.tsx
  frontend/src/app/components/experience/InclusionItem.tsx
Labels: Approved by: Brett, Approved by: John

#93 Booking availability and booking history improvements + backend cleaning
  backend/app/Http/Controllers/Api/V1/BookingController.php
  backend/app/Http/Controllers/Api/V1/ListingController.php
  backend/app/Models/Booking.php
  backend/app/Models/Listing.php
  frontend/src/app/(guest)/accommodations/[id]/checkout/page.tsx
  frontend/src/app/(guest)/accommodations/[id]/page.tsx
  frontend/src/app/(guest)/experiences/[id]/checkout/page.tsx
  frontend/src/app/(guest)/experiences/[id]/page.tsx
  frontend/src/app/(guest)/history/BookingHistoryComponent.tsx
  frontend/src/app/(guest)/history/page.tsx
  frontend/src/app/components/experience/InclusionSection.tsx
  frontend/src/app/components/review/ReviewSection.tsx
  frontend/src/app/components/svgs/Inclusions/TransportIcon.tsx
  frontend/src/app/utils/helpers/bookinghistory/request.ts
Labels: Code Review: Brett, Code Review: Faith, For Code Review

#94 Admin login markup
  frontend/src/app/(auth)/admin/login/AdminLoginForm.tsx
  frontend/src/app/(auth)/admin/login/page.tsx
  frontend/src/app/utils/helpers/adminHelper.ts
Labels: Approved by: Faith, Approved by: Rian

#95 update admin login
  backend/app/Claims/UserClaim.php
  backend/app/Http/Controllers/Api/V1/AdminAuthController.php
  backend/app/Http/Controllers/Api/V1/AuthController.php
  backend/app/Http/Controllers/Api/V1/GoogleAuthController.php
  backend/app/Http/Middleware/CheckUserRole.php
  backend/app/Http/Requests/V1/UserUpdateRequest.php
  backend/app/Models/Admin.php
  backend/app/Models/User.php
  backend/app/Providers/AuthServiceProvider.php
  backend/config/auth.php
  backend/routes/api.php
Labels: Approved by: Brett, Approved by: Cara

#96 Admin login integration
  frontend/src/app/(auth)/admin/login/AdminLoginForm.tsx
  frontend/src/app/components/home/host/ListingBookingsTable.tsx
  frontend/src/app/page.tsx
  frontend/src/app/utils/helpers/adminHelper.ts
  frontend/src/middleware.ts
Labels: Approved by: Brett, Approved by: Faith

#98 Markup - create components and pages for admin user management
  frontend/src/app/(admin)/users/UserComponent.tsx
  frontend/src/app/(admin)/users/page.tsx
  frontend/src/app/components/admin/AdminCard.tsx
  frontend/src/app/components/admin/BanConfirmModal.tsx
  frontend/src/app/components/admin/UserCard.tsx
  frontend/src/app/components/admin/UserGrid.tsx
Labels: Approved by: Brett, Approved by: John

#97 Task/report crud
  backend/app/Http/Controllers/Api/V1/ReportController.php
  backend/app/Http/Requests/V1/ReportRequest.php
  backend/app/Models/Report.php
  backend/database/migrations/2024_04_04_043358_update_reports_table.php
  backend/routes/api.php
Labels: Approved by: Cara, Approved by: Faith

#99 Backend - Create APIs for admin user management
  backend/app/Http/Controllers/Api/V1/AdminController.php
  backend/app/Http/Controllers/Api/V1/BanReasonController.php
  backend/app/Http/Controllers/Api/V1/UserController.php
  backend/app/Http/Requests/V1/BanRequest.php
  backend/app/Http/Requests/V1/UnbanRequest.php
  backend/app/Models/Admin.php
  backend/app/Models/BanReason.php
  backend/app/Models/User.php
  backend/database/migrations/2024_04_04_015320_create_ban_reasons_table.php
  backend/routes/api.php
Labels: Approved by: Brett, Approved by: Faith

#100 Request/booking add sort filter
  backend/app/Models/Booking.php
  frontend/src/app/(guest)/history/BookingHistoryComponent.tsx
  frontend/src/app/(guest)/history/BookingHistoryData.tsx
  frontend/src/app/(guest)/history/page.tsx
  frontend/src/app/components/BookingStatus.tsx
  frontend/src/app/components/home/host/FiltersSection.tsx
  frontend/src/app/components/home/host/ListingBookingsTable.tsx
  frontend/src/app/interfaces/types.ts
  frontend/src/app/utils/helpers/bookinghistory/request.ts
  frontend/src/app/utils/helpers/bookingmanagement/request.ts
Labels: Code Review: Rian, For Code Review, Approved by: Cara, Approved by: John

#104 Markup - Create components and pages for handling reports
  frontend/src/app/(admin)/reports/AdminReportComponent.tsx
  frontend/src/app/(admin)/reports/page.tsx
  frontend/src/app/components/admin/ActionConfirmModal.tsx
  frontend/src/app/components/admin/AdminCard.tsx
  frontend/src/app/components/admin/BanConfirmModal.tsx
  frontend/src/app/components/admin/ReportCard.tsx
  frontend/src/app/components/admin/ReportModal.tsx
  frontend/src/app/components/admin/ReportTabStatus.tsx
  frontend/src/app/components/admin/UserCard.tsx
  frontend/src/app/utils/enums.ts
Labels: Approved by: Brett, Approved by: John

#105 add admin analytics endpoint
  backend/app/Http/Controllers/Api/V1/AdminController.php
  backend/app/Models/Booking.php
  backend/app/Models/Listing.php
  backend/app/Models/User.php
  backend/composer.json
  backend/composer.lock
  backend/config/analytics.php
  backend/routes/api.php
  frontend/src/app/layout.tsx
Labels: Approved by: Brett, Approved by: Cara

#107 Integration - Call API from FE to approve/reject listings
  backend/app/Http/Controllers/Api/V1/AccommodationController.php
  backend/app/Http/Controllers/Api/V1/BookingController.php
  backend/app/Http/Controllers/Api/V1/ExperienceController.php
  backend/app/Http/Controllers/Api/V1/ListingController.php
  backend/app/Http/Controllers/Api/V1/UserController.php
  backend/app/Models/Listing.php
  backend/app/Models/User.php
  backend/app/Traits/ResponseHandlingTrait.php
  frontend/src/app/(admin)/approvals/accommodation/[id]/page.tsx
  frontend/src/app/(admin)/approvals/experience/[id]/page.tsx
  frontend/src/app/(admin)/dashboard/page.tsx
  frontend/src/app/components/admin/AdminApprover.tsx
  frontend/src/app/components/admin/ConfirmModal.tsx
  frontend/src/app/interfaces/ModalProps.ts
  frontend/src/app/utils/helpers/approval/request.ts
Labels: Approved by: Brett, Approved by: Faith, Approved by: John

#108 Admin Analytics markup
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/(admin)/dashboard/AdminAnalytics.tsx
  frontend/src/app/(admin)/dashboard/page.tsx
  frontend/src/app/components/admin/ConfirmModal.tsx
  frontend/src/app/components/admin/ListingDoughnut.tsx
  frontend/src/app/components/admin/PopularListingCard.tsx
  frontend/src/app/components/admin/PopularListingsSection.tsx
  frontend/src/app/components/admin/UserTrafficSection.tsx
  frontend/src/app/components/svgs/Admin/BookingsIcon.tsx
  frontend/src/app/components/svgs/Admin/ListingsIcon.tsx
  frontend/src/app/components/svgs/Admin/UsersIcon.tsx
Labels: Approved by: Faith, Approved by: Rian

#109 make calendar page mobile responsive
  frontend/src/app/(host)/calendar/page.tsx
  frontend/src/app/components/calendar/AvailabilityCalendar.tsx
  frontend/src/app/components/calendar/AvailabilitySidebar.tsx
Labels: Code Review: John, For Code Review, Approved by: Rian

#110 add admin analytics funtionality
  backend/app/Models/User.php
  frontend/src/app/(admin)/dashboard/AdminAnalytics.tsx
  frontend/src/app/(admin)/dashboard/page.tsx
  frontend/src/app/components/admin/PopularListingCard.tsx
  frontend/src/app/components/admin/PopularListingsSection.tsx
  frontend/src/app/components/admin/UserTrafficSection.tsx
  frontend/src/app/components/navbar/NavbarLinks.tsx
  frontend/src/app/interfaces/types.ts
  frontend/src/app/utils/helpers/adminHelper.ts
Labels: Code Review: John, Code Review: Rian, For Code Review

#111 Task/report crud integration
  backend/app/Models/Report.php
  frontend/src/app/(admin)/reports/AdminReportComponent.tsx
  frontend/src/app/(admin)/reports/page.tsx
  frontend/src/app/components/ReportModal.tsx
  frontend/src/app/components/admin/ActionConfirmModal.tsx
  frontend/src/app/components/admin/ReportCard.tsx
  frontend/src/app/components/admin/ReportDetailsModal.tsx
  frontend/src/app/components/admin/ReportModal.tsx
  frontend/src/app/components/admin/ReportTabStatus.tsx
  frontend/src/app/components/booking/AccommodationBookingSticky.tsx
  frontend/src/app/components/booking/ExperienceBookingSticky.tsx
  frontend/src/app/interfaces/types.ts
  frontend/src/app/utils/enums.ts
  frontend/src/app/utils/helpers/report/request.ts
  frontend/src/app/utils/helpers/report/validation.ts
Labels: Approved by: John, Approved by: Rian

#112 Integration - Search and filter listings
  backend/app/Models/Listing.php
  frontend/src/app/(admin)/approvals/ListingsGrid.tsx
  frontend/src/app/(admin)/approvals/page.tsx
  frontend/src/app/utils/helpers/approval/request.ts
Labels: Code Review: John, Code Review: Faith, For Code Review

#113 Implement mobile responsive user profile page
  frontend/src/app/(shared)/profile/EmailField.tsx
  frontend/src/app/(shared)/profile/LegalNameField.tsx
  frontend/src/app/(shared)/profile/PasswordField.tsx
  frontend/src/app/(shared)/profile/ProfileComponent.tsx
  frontend/src/app/(shared)/profile/page.tsx
  frontend/src/app/interfaces/ProfileFieldProps.ts
  frontend/src/app/utils/helpers/adminHelper.ts
Labels: Code Review: Rian, For Code Review, Approved by: Faith

#114 added some fixes to the ui
  frontend/src/app/components/admin/ReportDetailsModal.tsx
Labels: Code Review: John, Code Review: Rian, For Code Review

#115 Backend - Add filter, sort, and search for user management
  backend/app/Enums/UserStatus.php
  backend/app/Http/Controllers/Api/V1/AdminController.php
  backend/app/Http/Requests/V1/UserSortRequest.php
  backend/app/Models/Admin.php
Labels: Approved by: Brett, Approved by: Rian

#116 add mobile responsiveness to guest history page
  frontend/src/app/(guest)/history/BookingHistoryComponent.tsx
  frontend/src/app/(guest)/history/BookingHistoryData.tsx
  frontend/src/app/components/home/host/FiltersSection.tsx
Labels: Code Review: Brett, Code Review: Rian, For Code Review

#117 Mobile responsiveness for Sign Up page
  .gitignore
  backend/.gitignore
  frontend/src/app/(auth)/role-selection/page.tsx
  frontend/src/app/(auth)/signup/SignUpForm.tsx
  frontend/src/app/components/RadioCard.tsx
  frontend/src/app/components/RoleSelectForm.tsx
  frontend/src/app/utils/helpers/adminHelper.ts
Labels: Approved by: Faith, Approved by: Rian

#118 Set listing status back to pending on edit
  backend/app/Http/Controllers/Api/V1/AccommodationController.php
  backend/app/Models/Experience.php
  backend/app/Models/Listing.php
  frontend/src/app/(host)/listings/accommodations/[id]/edit/EditListingComponent.tsx
  frontend/src/app/(host)/listings/experiences/[id]/edit/EditExperienceComponent.tsx
Labels: Approved by: Brett, Approved by: John, Approved by: Rian

#119 Integration - Call APIs from FE to integrate admin user management
  backend/app/Http/Controllers/Api/V1/AdminController.php
  frontend/src/app/(admin)/reports/AdminReportComponent.tsx
  frontend/src/app/(admin)/users/UserComponent.tsx
  frontend/src/app/(admin)/users/page.tsx
  frontend/src/app/components/admin/BanConfirmModal.tsx
  frontend/src/app/components/admin/UserAdminCard.tsx
  frontend/src/app/components/admin/UserCard.tsx
  frontend/src/app/components/admin/UserGrid.tsx
  frontend/src/app/components/admin/UserGuestCard.tsx
  frontend/src/app/components/admin/UserHostCard.tsx
  frontend/src/app/interfaces/types.ts
  frontend/src/app/utils/helpers/admin/request.ts
Labels: Approved by: Brett, Approved by: John

#120 make host home page mobile responsive
  frontend/src/app/(guest)/history/BookingHistoryComponent.tsx
  frontend/src/app/(guest)/history/BookingHistoryData.tsx
  frontend/src/app/components/home/host/FiltersSection.tsx
  frontend/src/app/components/home/host/HostDashboard.tsx
  frontend/src/app/components/home/host/ListingBookingsTable.tsx
  frontend/src/app/components/home/host/PendingCardsSlicer.tsx
  frontend/src/app/components/home/host/PendingListModal.tsx
  frontend/src/app/components/home/host/PendingListingCard.tsx
Labels: Approved by: Brett, Approved by: Rian

#123 Mobile/experience edit new
  frontend/src/app/(host)/listings/experiences/[id]/edit/EditExperienceForm.tsx
  frontend/src/app/(host)/listings/experiences/new/NewExperienceForm.tsx
Labels: Approved by: John, Approved by: Rian

#122 Mobile - Implement mobile responsive guest checkout booking page
  frontend/src/app/components/booking/AccommodationBookingConfirm.tsx
  frontend/src/app/components/booking/ExperienceBookingConfirm.tsx
Labels: Code Review: Faith, Code Review: Rian, For Code Review

#124 make sticky booking section mobile responsive
  frontend/src/app/(guest)/accommodations/[id]/page.tsx
  frontend/src/app/(guest)/experiences/[id]/page.tsx
  frontend/src/app/components/booking/AccommodationBookingSticky.tsx
  frontend/src/app/components/booking/DefaultSticky.tsx
  frontend/src/app/components/booking/ExperienceBookingSticky.tsx
Labels: Approved by: Cara

#125 Mobile - Implement mobile responsive admin user management page
  frontend/src/app/components/admin/AdminCard.tsx
  frontend/src/app/components/admin/UserAdminCard.tsx
  frontend/src/app/components/admin/UserGrid.tsx
  frontend/src/app/components/admin/UserGuestCard.tsx
  frontend/src/app/components/admin/UserHostCard.tsx
Labels: Code Review: John

#126 Mobile - Implement admin reports management page
  frontend/src/app/(admin)/reports/AdminReportComponent.tsx
  frontend/src/app/components/admin/ReportCard.tsx
  frontend/src/app/components/admin/ReportDetailsModal.tsx
  frontend/src/app/components/admin/ReportTabStatus.tsx
  frontend/src/app/components/admin/UserGrid.tsx
Labels: Approved by: John

#127 Mobile - Implement mobile responsive experience details page
  frontend/src/app/components/experience/ExperienceHeader.tsx
  frontend/src/app/components/experience/InclusionSection.tsx
  frontend/src/app/components/review/ReviewPaginate.tsx
Labels: Approved by: Faith, Approved by: John

#128 Mobile - Implement mobile responsive for admin dashboard
  frontend/src/app/(admin)/dashboard/AdminAnalytics.tsx
  frontend/src/app/components/admin/PopularListingCard.tsx
  frontend/src/app/components/admin/PopularListingsSection.tsx
Labels: Approved by: Faith

#129 Mobile - Implement mobile responsive admin listings approval
  frontend/src/app/(admin)/approvals/ListingsGrid.tsx
  frontend/src/app/(admin)/approvals/accommodation/[id]/page.tsx
  frontend/src/app/(admin)/approvals/experience/[id]/page.tsx
  frontend/src/app/(admin)/approvals/page.tsx
  frontend/src/app/(admin)/reports/AdminReportComponent.tsx
  frontend/src/app/(admin)/users/UserComponent.tsx
  frontend/src/app/(host)/listings/accommodations/[id]/edit/EditListingComponent.tsx
  frontend/src/app/components/admin/AdminApprover.tsx
Labels: Approved by: Cara, Approved by: John

#130 check user status upon login
  backend/app/Http/Controllers/Api/V1/AuthController.php
  backend/app/Models/Admin.php
  backend/app/Models/User.php
  backend/app/Traits/ResponseHandlingTrait.php
  frontend/src/app/(guest)/history/BookingHistoryComponent.tsx
  frontend/src/app/(guest)/history/BookingHistoryData.tsx
Labels: Approved by: John, Approved by: Rian

#132 Mobile - Implement mobile responsive accommodation details page
  frontend/src/app/(guest)/accommodations/[id]/page.tsx
  frontend/src/app/(guest)/experiences/[id]/page.tsx
  frontend/src/app/(host)/listings/accommodations/[id]/page.tsx
  frontend/src/app/(host)/listings/experiences/[id]/page.tsx
  frontend/src/app/components/accommodation/AmenitySection.tsx
  frontend/src/app/components/accommodation/ListingHeader.tsx
  frontend/src/app/components/experience/ExperienceHeader.tsx
  frontend/src/app/components/review/ReviewComponent.tsx
  frontend/src/app/components/review/ReviewHeader.tsx
Labels: Approved by: Faith, Approved by: John

#133 persist listing filters on page reload
  frontend/src/app/components/listings/ListingSearchBar.tsx
Labels: Approved by: Cara

#134 Integration - Display warning containing reason of ban on login of banned user on FE
  frontend/src/app/(admin)/approvals/ListingsGrid.tsx
  frontend/src/app/(admin)/approvals/accommodation/[id]/page.tsx
  frontend/src/app/(admin)/approvals/experience/[id]/page.tsx
  frontend/src/app/(admin)/reports/AdminReportComponent.tsx
  frontend/src/app/(admin)/users/UserComponent.tsx
  frontend/src/app/(auth)/login/LoginComponent.tsx
  frontend/src/app/(auth)/login/LoginForm.tsx
  frontend/src/app/(auth)/login/page.tsx
  frontend/src/app/api/auth/[...nextauth]/nextAuthOptions.ts
  frontend/src/app/components/accommodation/ListingHeader.tsx
  frontend/src/app/components/admin/AdminApprover.tsx
  frontend/src/app/components/admin/AdminUserManagementFilter.tsx
  frontend/src/app/components/admin/ReportFilterComponent.tsx
  frontend/src/app/components/admin/UserGrid.tsx
  frontend/src/app/components/admin/UserGuestCard.tsx
  frontend/src/app/components/admin/UserHostCard.tsx
  frontend/src/app/components/experience/ExperienceHeader.tsx
  frontend/src/app/utils/helpers/userHelper.ts
Labels: Approved by: Brett, Approved by: John

#135 Backend - Apply response trait and refactor code on searching users
  backend/app/Http/Controllers/Api/V1/AdminController.php
  backend/app/Http/Controllers/Api/V1/BookingController.php
  backend/app/Http/Controllers/Api/V1/ListingController.php
  backend/app/Http/Controllers/Api/V1/SessionController.php
  backend/app/Http/Controllers/Api/V1/UserController.php
  backend/app/Models/Admin.php
  backend/app/Traits/ResponseHandlingTrait.php
Labels: Approved by: Faith

#136 Report and User Ban does not refresh on update.
  frontend/src/app/(admin)/reports/AdminReportComponent.tsx
  frontend/src/app/(admin)/users/UserComponent.tsx
  frontend/src/app/components/accommodation/ListingHeader.tsx
  frontend/src/app/components/admin/BanConfirmModal.tsx
  frontend/src/app/components/experience/ExperienceHeader.tsx
Labels: Approved by: Cara, Approved by: John

#137 Updated middleware
  frontend/src/app/(auth)/login/LoginForm.tsx
  frontend/src/middleware.ts
Labels: Approved by: Faith
